### ISSUE TITLE
Is match-directories correct?

### ISSUE THREAD

**Issue by mithro** [google/skywater-pdk-actions#25]
The description for match-directories says it is a regex which should match the subdirectory name under `cells`. See;

https://github.com/google/skywater-pdk-actions/blob/77e8b4541c096e11b24046b3fb6cd99378f6d061/run-drc-for-cell-gds-using-magic/run_all_drc.py#L144-L150

However, the regex `.` should will only match a single character -- this any cell with two letters in its name (which is all of them) should not match. If you want to match anything the default regex should be `.*`.

**Comment by donn** [comment]
Well, I don't particularly know why you closed this, but for the future, the answer is no.

/./ matches anything with one character or more. It's /^.$/ that will match only one character. Regexes do not, by default, compare the regex to the entire string.

**Comment by mithro** [comment]
@donn -- 
> **re.match(pattern, string, flags=0)**
> If zero or more characters at the beginning of string match the regular expression pattern, return a corresponding match object. 

I fixed this in https://github.com/google/skywater-pdk-actions/pull/26/commits/c9a499e255cc33639e6f33a4e35571a675aaa24a and https://github.com/google/skywater-pdk-actions/pull/26/commits/fa2b71e53d72662a90d355b741edbf9269043159
